// Fiesta — playful: magenta vivo (separado del índigo de marca), esquinas bien
// redondeadas, sombras con tinte de color, íconos rellenos y Baloo 2.

const fiesta = {
  id: 'fiesta',
  name: 'Fiesta',
  tagline: 'Colorido y juguetón',
  isDark: false,
  statusBar: { onBackground: 'dark', onHeader: 'dark' },
  icons: { variant: 'filled' },
  colors: {
    background: '#f6f2fb',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    text: '#2d2440',
    textMuted: '#5f5578',
    textFaint: '#6d6483',
    primary: '#a626aa',
    onPrimary: '#ffffff',
    primarySoft: '#f8e8f9',
    primarySoftBorder: '#eac9ec',
    primaryDisabled: '#d79ad9',
    accent: '#a95a00',
    accentSoft: '#fdf0dc',
    border: '#e6def2',
    danger: '#c22f52',
    dangerSoft: '#fdedf1',
    overlay: 'rgba(45, 36, 64, 0.55)',
    headerBackground: '#f6f2fb',
    onHeader: '#2d2440',
    tabBarBackground: '#ffffff',
    tabBarBorder: '#e6def2',
    tabActive: '#a626aa',
    tabInactive: '#5f5578',
    moods: {
      FELIZ:   { color: '#a95a00', soft: '#fdf0dc' },
      TRISTE:  { color: '#3b63d8', soft: '#eaeffd' },
      ANSIOSO: { color: '#b93d0b', soft: '#fde8dc' },
      CALMADO: { color: '#0c7568', soft: '#dcf5f2' },
      ENOJADO: { color: '#c22f52', soft: '#fdedf1' },
      NEUTRO:  { color: '#655d7a', soft: '#edeaf4' },
    },
    categories: {
      social: '#3b63d8',
      físico: '#b93d0b',
      creativo: '#8f2fbf',
      relajación: '#0779a3',
      reflexión: '#0f7d3c',
      entretenimiento: '#c22f52',
      productividad: '#a95a00',
      mindfulness: '#0c7568',
    },
  },
  typography: {
    scale: 1,
    fonts: {
      regular: { fontFamily: 'Baloo2_400Regular' },
      medium: { fontFamily: 'Baloo2_500Medium' },
      semibold: { fontFamily: 'Baloo2_600SemiBold' },
      bold: { fontFamily: 'Baloo2_700Bold' },
    },
    type: {
      display: { fontFamily: 'Sora_700Bold', fontSize: 28, lineHeight: 34 },
      title: { fontFamily: 'Sora_700Bold', fontSize: 20, lineHeight: 26 },
      section: { fontFamily: 'Sora_600SemiBold', fontSize: 16, lineHeight: 22 },
      body: { fontFamily: 'Baloo2_500Medium', fontSize: 15, lineHeight: 23 },
      caption: { fontFamily: 'Baloo2_400Regular', fontSize: 12, lineHeight: 17 },
    },
  },
  shape: {
    radiusSm: 12,
    radiusMd: 14,
    radiusLg: 18,
    radiusXl: 26,
    borderThin: 1,
    borderMedium: 1.5,
    borderThick: 2,
  },
  shadows: {
    card: {
      shadowColor: '#a626aa',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 2,
    },
    cardStrong: {
      shadowColor: '#a626aa',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.16,
      shadowRadius: 8,
      elevation: 3,
    },
    modal: {
      shadowColor: '#2d2440',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 8,
    },
  },
};

export default fiesta;
