// Nocturno — el lado oscuro de "Hora Azul": índigo profundo por capas de
// superficie (no negro plano), acento índigo claro y coral suave. En oscuro
// las sombras no se ven: la separación la dan las capas.

const nocturno = {
  id: 'nocturno',
  name: 'Nocturno',
  tagline: 'Oscuro y descansado',
  isDark: true,
  statusBar: { onBackground: 'light', onHeader: 'light' },
  icons: { variant: 'outline' },
  colors: {
    background: '#12141c',
    surface: '#1a1d28',
    surfaceElevated: '#242838',
    text: '#e7e9f0',
    textMuted: '#a6adc2',
    textFaint: '#8e96ad',
    primary: '#93a3f0',
    onPrimary: '#101430',
    primarySoft: '#232a4a',
    primarySoftBorder: '#39436b',
    primaryDisabled: '#4a5378',
    accent: '#f0977a',
    accentSoft: '#3a2620',
    border: '#2c3040',
    danger: '#ef8080',
    dangerSoft: '#3a2222',
    overlay: 'rgba(0, 0, 0, 0.6)',
    headerBackground: '#12141c',
    onHeader: '#e7e9f0',
    tabBarBackground: '#1a1d28',
    tabBarBorder: '#2c3040',
    tabActive: '#93a3f0',
    tabInactive: '#a6adc2',
    moods: {
      FELIZ:   { color: '#e2b25c', soft: '#3a2f18' },
      TRISTE:  { color: '#8fb4ec', soft: '#1e2a40' },
      ANSIOSO: { color: '#f0a36a', soft: '#3d2a1a' },
      CALMADO: { color: '#6fd0c2', soft: '#173733' },
      ENOJADO: { color: '#f08a8a', soft: '#3a2222' },
      NEUTRO:  { color: '#a9b2c4', soft: '#262b38' },
    },
    categories: {
      social: '#8fb4ec',
      físico: '#f0a36a',
      creativo: '#c49ae0',
      relajación: '#66c7d4',
      reflexión: '#93a3f0',
      entretenimiento: '#f08a8a',
      productividad: '#e2b25c',
      mindfulness: '#6fd0c2',
    },
  },
  typography: {
    scale: 1,
    fonts: {
      regular: { fontFamily: 'Manrope_400Regular' },
      medium: { fontFamily: 'Manrope_500Medium' },
      semibold: { fontFamily: 'Manrope_600SemiBold' },
      bold: { fontFamily: 'Manrope_700Bold' },
    },
    type: {
      display: { fontFamily: 'Sora_700Bold', fontSize: 28, lineHeight: 34 },
      title: { fontFamily: 'Sora_700Bold', fontSize: 20, lineHeight: 26 },
      section: { fontFamily: 'Sora_600SemiBold', fontSize: 16, lineHeight: 22 },
      body: { fontFamily: 'Manrope_500Medium', fontSize: 15, lineHeight: 23 },
      caption: { fontFamily: 'Manrope_400Regular', fontSize: 12, lineHeight: 17 },
    },
  },
  shape: {
    radiusSm: 8,
    radiusMd: 11,
    radiusLg: 14,
    radiusXl: 20,
    borderThin: 1,
    borderMedium: 1.5,
    borderThick: 2,
  },
  shadows: {
    card: {},
    cardStrong: {},
    modal: {},
  },
};

export default nocturno;
