// Sereno — tema por defecto de la identidad "Hora Azul": índigo sereno sobre
// niebla fría, con coral quemado como acento cálido. Header claro: el color va
// en las acciones, no en franjas. Todos los pares cumplen WCAG AA (tests).

const sereno = {
  id: 'sereno',
  name: 'Sereno',
  tagline: 'Claro y minimalista',
  isDark: false,
  statusBar: { onBackground: 'dark', onHeader: 'dark' },
  icons: { variant: 'outline' },
  colors: {
    background: '#f5f6fa',
    surface: '#ffffff',
    surfaceElevated: '#ffffff',
    text: '#232a3d',
    textMuted: '#565f72',
    textFaint: '#636c7e',
    primary: '#4a5fc1',
    onPrimary: '#ffffff',
    primarySoft: '#e9ecf9',
    primarySoftBorder: '#c9d2f0',
    primaryDisabled: '#a7b2e2',
    accent: '#b34c30',
    accentSoft: '#fceee9',
    border: '#e3e6ef',
    danger: '#c62828',
    dangerSoft: '#fdeaea',
    overlay: 'rgba(20, 24, 38, 0.55)',
    headerBackground: '#f5f6fa',
    onHeader: '#232a3d',
    tabBarBackground: '#ffffff',
    tabBarBorder: '#e3e6ef',
    tabActive: '#4a5fc1',
    tabInactive: '#565f72',
    moods: {
      FELIZ:   { color: '#8a6000', soft: '#f8efdc' },
      TRISTE:  { color: '#3d6bb5', soft: '#e8eef9' },
      ANSIOSO: { color: '#b84800', soft: '#fdeee2' },
      CALMADO: { color: '#00695c', soft: '#e0f2ef' },
      ENOJADO: { color: '#c62828', soft: '#fdeaea' },
      NEUTRO:  { color: '#5d6570', soft: '#eef0f4' },
    },
    categories: {
      social: '#3d6bb5',
      físico: '#b84800',
      creativo: '#7d3f9e',
      relajación: '#00707b',
      reflexión: '#4a5fc1',
      entretenimiento: '#c62828',
      productividad: '#8a6000',
      mindfulness: '#00695c',
    },
  },
  typography: {
    scale: 1,
    fonts: {
      regular: { fontFamily: 'Manrope_400Regular' },
      medium: { fontFamily: 'Manrope_500Medium' },
      semibold: { fontFamily: 'Manrope_600SemiBold' },
      bold: { fontFamily: 'Manrope_700Bold' },
    },
    type: {
      display: { fontFamily: 'Sora_700Bold', fontSize: 28, lineHeight: 34 },
      title: { fontFamily: 'Sora_700Bold', fontSize: 20, lineHeight: 26 },
      section: { fontFamily: 'Sora_600SemiBold', fontSize: 16, lineHeight: 22 },
      body: { fontFamily: 'Manrope_500Medium', fontSize: 15, lineHeight: 23 },
      caption: { fontFamily: 'Manrope_400Regular', fontSize: 12, lineHeight: 17 },
    },
  },
  shape: {
    radiusSm: 8,
    radiusMd: 11,
    radiusLg: 14,
    radiusXl: 20,
    borderThin: 1,
    borderMedium: 1.5,
    borderThick: 2,
  },
  shadows: {
    card: {
      shadowColor: '#232a3d',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    cardStrong: {
      shadowColor: '#232a3d',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    modal: {
      shadowColor: '#232a3d',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.16,
      shadowRadius: 12,
      elevation: 8,
    },
  },
};

export default sereno;
